<template>
  <div class="pro-page page-animate"><div class="wrap">
    <section class="football-hero bot-hero"><div><span class="eyebrow">BraTipsters daily intelligence</span><h1>Bet of the Day</h1><p>Featured football selections with explicit markets, model confidence and a direct route into the Match Centre.</p></div><div class="bot-badge">★ DAILY FEATURE</div></section>
    <section v-if="items.length" class="bot-grid"><RouterLink v-for="p in items" :key="p._id" :to="betPath(p)" class="bot-pro-card"><div class="bot-card-top"><span class="tag">{{p.risk||'Featured'}}</span><span v-if="p.status==='won'" class="result-badge won">WON</span><span v-else-if="p.status==='lost'" class="result-badge lost">LOST</span><span v-else class="live-label">FEATURED</span></div><div class="bot-fixture"><div><TeamLogo :src="p.matchId?.homeTeamId?.logo" :name="p.matchId?.homeTeamId?.name" size="lg"/><b>{{p.matchId?.homeTeamId?.name||'Home'}}</b></div><span>VS</span><div><TeamLogo :src="p.matchId?.awayTeamId?.logo" :name="p.matchId?.awayTeamId?.name" size="lg"/><b>{{p.matchId?.awayTeamId?.name||'Away'}}</b></div></div><div class="bot-selection"><small>Recommended market</small><strong>{{p.prediction}}</strong><span v-if="p.odds">Reference odds <b>{{formatOdds(p.odds)}}</b></span></div><div class="bot-card-stats"><div><span>Confidence</span><b>{{p.confidence||'—'}}%</b></div><div><span>Model</span><b>{{p.model||'AI model'}}</b></div><div><span>Status</span><b>{{p.status}}</b></div></div><p>{{p.analysis||'Featured football selection from the BraTipsters model.'}}</p><span class="bot-open">Open match intelligence →</span></RouterLink></section>
    <EmptyState v-else title="Bet of the Day is not published yet" message="There is no featured selection available right now. Check back when the next football slate is reviewed." icon="★" />
    <section class="recent-results-card"><div class="pro-section-head"><div><span class="eyebrow">Recently played</span><h2>Past Bet of the Day results</h2></div><RouterLink to="/history">All prediction history →</RouterLink></div><div v-if="recent.length" class="recent-result-list"><RouterLink v-for="p in recent" :key="p._id" :to="betPath(p)" class="recent-result-row"><span :class="['result-badge',p.status]">{{String(p.status).toUpperCase()}}</span><div class="recent-result-teams"><div><TeamLogo :src="p.matchId?.homeTeamId?.logo" :name="p.matchId?.homeTeamId?.name" size="xs"/><b>{{p.matchId?.homeTeamId?.shortName||p.matchId?.homeTeamId?.name||'Home'}}</b></div><strong v-if="p.matchId?.status==='finished'" class="recent-score">{{p.matchId?.homeScore}} : {{p.matchId?.awayScore}}</strong><span v-else>vs</span><div><b>{{p.matchId?.awayTeamId?.shortName||p.matchId?.awayTeamId?.name||'Away'}}</b><TeamLogo :src="p.matchId?.awayTeamId?.logo" :name="p.matchId?.awayTeamId?.name" size="xs"/></div><small>{{p.prediction}}</small></div><strong class="recent-odds">{{formatOdds(p.odds)}}</strong><span>→</span></RouterLink></div><EmptyState v-else title="No Bet of the Day results yet" message="Played featured selections will appear here automatically after results are settled." icon="✓" compact /></section>
    <section class="bot-disclaimer"><span>i</span><p>Bet of the Day is informational and does not guarantee a result. Always review the full Match Centre before making decisions.</p></section>
  </div></div>
</template>
<script setup lang="ts">import {onMounted,ref} from 'vue';import {RouterLink} from 'vue-router';import {api} from '../services/api';import TeamLogo from '../components/TeamLogo.vue';import EmptyState from '../components/EmptyState.vue';import {formatOdds} from '../utils/formatters';import {useToast} from '../composables/feedback';const items=ref<any[]>([]),recent=ref<any[]>([]),{show:toast}=useToast();const betPath=(p:any)=>p.matchId?._id?`/matches/${p.matchId._id}`:'/bet-of-the-day';onMounted(async()=>{try{const d=await api.get('/bet-of-day');items.value=(d.data||[]).filter((x:any)=>['published','won','lost','void'].includes(x.status))}catch{toast('The featured selection could not be loaded.','error','Bet of the Day')}try{const d=await api.get('/bet-of-day/recent?limit=8');recent.value=d.data||[]}catch{toast('Recent featured results could not be loaded.','error','Bet of the Day')}});</script>
