<template>
  <div class="pro-page dashboard-pro page-animate"><div class="wrap">
    <section class="dashboard-welcome"><div><span class="eyebrow">Personal workspace</span><h1>Welcome back, {{auth.user?.name||'there'}}.</h1><p>Track your selections, notifications and tipster tools from one football workspace.</p></div><RouterLink to="/picks" class="btn">Browse latest tips</RouterLink></section>
    <section class="dash-kpis"><div><span>My picks</span><strong>{{picks.length}}</strong><small>tracked selections</small></div><div><span>Open</span><strong>{{openPicks}}</strong><small>awaiting results</small></div><div><span>Won</span><strong>{{wonPicks}}</strong><small>settled wins</small></div><div><span>Notifications</span><strong>{{unread}}</strong><small>unread updates</small></div></section>
    <div class="dashboard-grid"><main>
      <section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">My selections</span><h2>Tracked picks</h2></div><RouterLink to="/history">Public results →</RouterLink></div><div v-if="picks.length" class="my-pick-list"><div v-for="x in picks" :key="x._id" class="my-pick-row"><div><span :class="['result-badge',x.status]">{{x.status}}</span></div><div class="my-pick-fixture"><b>{{x.predictionId?.fixture||'Football match'}}</b><span>{{x.predictionId?.prediction}}</span></div><div><small>Odds</small><b>{{Number(x.predictionId?.odds||0).toFixed(2)}}</b></div><div><small>Stake</small><b>GHS {{Number(x.stake||0).toFixed(2)}}</b></div><button v-if="x.status==='open'" class="ghost" @click="remove(x._id)">Remove</button></div></div><div v-else class="empty">You have no tracked picks yet. <RouterLink to="/picks">Explore the latest predictions →</RouterLink></div></section>
      <section v-if="auth.isTipster" class="pro-panel tipster-workspace"><div class="pro-section-head"><div><span class="eyebrow">Tipster workspace</span><h2>Submit a prediction</h2></div><span>Admin review required</span></div><div class="tipster-submit-grid"><form @submit.prevent="submitPrediction"><div class="field"><label>Fixture</label><input v-model="form.fixture" required placeholder="Home vs Away"/></div><div class="two-fields"><div class="field"><label>Prediction</label><input v-model="form.prediction" required placeholder="Double Chance 1X"/></div><div class="field"><label>Odds</label><input v-model.number="form.odds" type="number" min="1" step=".01" required/></div></div><div class="field"><label>Confidence</label><input v-model.number="form.confidence" type="number" min="0" max="100"/></div><div class="field"><label>Analysis</label><textarea v-model="form.analysis" placeholder="Explain the football reasoning behind the selection."/></div><button class="btn">Submit for review</button><div v-if="message" class="success">{{message}}</div></form><div class="tipster-record"><span class="eyebrow">Your record</span><h3>{{tipster?.username||'Tipster'}}</h3><div class="record-grid"><div><b>{{tipster?.totalTips||0}}</b><span>Tips</span></div><div><b>{{tipster?.wins||0}}</b><span>Wins</span></div><div><b>{{tipster?.currentStreak||0}}</b><span>Streak</span></div><div><b>{{tipster?.longestStreak||0}}</b><span>Best</span></div></div></div></div></section>
    </main><aside>
      <section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Notifications</span><h2>Activity</h2></div><button class="ghost" @click="markAll">{{unread?'Mark all read':'All read'}}</button></div><div v-if="notifications.length" class="activity-list"><div v-for="n in notifications.slice(0,8)" :key="n._id" :class="['activity-item',{unread:!n.read}]" @click="read(n)"><span class="activity-dot"></span><div><b>{{n.title}}</b><p>{{n.message}}</p><small>{{new Date(n.createdAt).toLocaleString()}}</small></div></div></div><div v-else class="empty compact">No recent notifications.</div></section>
      <section class="quick-links"><RouterLink to="/matches"><span>⚽</span><div><b>Football Centre</b><small>Live scores & fixtures</small></div><strong>→</strong></RouterLink><RouterLink to="/dropping-odds"><span>↘</span><div><b>Dropping Odds</b><small>Market movement</small></div><strong>→</strong></RouterLink><RouterLink to="/bet-of-the-day"><span>★</span><div><b>Bet of the Day</b><small>Daily featured picks</small></div><strong>→</strong></RouterLink><RouterLink to="/subscription"><span>✦</span><div><b>Premium</b><small>Deeper football research</small></div><strong>→</strong></RouterLink></section>
    </aside></div>
  </div></div>
</template>
<script setup lang="ts">import {computed,onMounted,reactive,ref} from 'vue';import {RouterLink} from 'vue-router';import {useAuth} from '../stores/auth';import {api} from '../services/api';const auth=useAuth(),picks=ref<any[]>([]),notifications=ref<any[]>([]),unread=ref(0),tipster=ref<any>(null),message=ref('');const form=reactive<any>({fixture:'',prediction:'',odds:1.5,confidence:80,analysis:''});const openPicks=computed(()=>picks.value.filter(x=>x.status==='open').length),wonPicks=computed(()=>picks.value.filter(x=>x.status==='won').length);async function load(){try{const n=await api.get('/me/notifications');notifications.value=n.data||[];unread.value=n.unread||0}catch{}try{picks.value=(await api.get('/me/picks')).data||[]}catch{}if(auth.isTipster)try{tipster.value=(await api.get('/me/tipster')).data.profile}catch{}}async function read(n:any){if(!n.read){try{await api.patch(`/me/notifications/${n._id}/read`,{});n.read=true;unread.value=Math.max(0,unread.value-1)}catch{}}}async function markAll(){try{await api.patch('/me/notifications/read-all',{});notifications.value.forEach(n=>n.read=true);unread.value=0}catch{}}async function remove(id:string){try{await api.delete(`/me/picks/${id}`);await load()}catch{}}async function submitPrediction(){try{const d=await api.post('/me/tipster/predictions',form);message.value=d.message;Object.assign(form,{fixture:'',prediction:'',odds:1.5,confidence:80,analysis:''})}catch(e:any){message.value=e?.message||'Unable to submit prediction.'}}onMounted(load);</script>
