<template>
  <div class="pro-page tipster-dashboard page-animate"><div class="wrap">
    <template v-if="auth.isTipster">
      <section class="td-hero">
        <div class="td-hero-main">
          <div class="td-avatar">{{ initials(tipster?.username || auth.user?.name || 'T') }}</div>
          <div><span class="eyebrow">Tipster control centre</span><h1>{{ tipster?.username || auth.user?.name || 'Tipster' }}</h1><p>Manage your football selections, monitor performance and keep your publishing pipeline moving.</p><div class="td-status"><i></i> Active tipster account <span>•</span> Admin review enabled</div></div>
        </div>
        <div class="td-hero-actions"><RouterLink to="/tipsters" class="ghost">View tipsters</RouterLink><button v-if="upcomingMatches.length" class="btn" @click="focusSubmit">+ New prediction</button></div>
      </section>

      <section class="td-wallet pro-panel">
        <div class="td-wallet-head"><div><span class="eyebrow">Tipster earnings</span><h2>Performance wallet</h2><p>Rewards come from BraTipsters subscription revenue. This is not a user betting wallet. Withdrawals are reviewed and paid manually by BraTipsters. Approved payouts are processed within 1–3 business days.</p></div><span class="td-wallet-badge">{{ wallet?.settings?.tipsterPoolPercent || 30 }}% TIPSTER POOL</span></div>
        <div class="td-wallet-grid">
          <div><small>Available</small><strong>{{ money(wallet?.wallet?.availableBalance) }}</strong><span>Eligible for withdrawal</span></div>
          <div><small>Pending</small><strong>{{ money(wallet?.wallet?.pendingBalance) }}</strong><span>Under review</span></div>
          <div><small>Lifetime earned</small><strong>{{ money(wallet?.wallet?.lifetimeEarned) }}</strong><span>Performance rewards</span></div>
          <div><small>Withdrawn</small><strong>{{ money(wallet?.wallet?.lifetimeWithdrawn) }}</strong><span>Completed payouts</span></div>
        </div>
        <div class="td-wallet-actions">
          <div><b>How rewards work</b><span>At month end, {{ wallet?.settings?.tipsterPoolPercent || 30 }}% of collected subscription revenue is distributed to eligible tipsters using the published performance formula. You need at least {{ wallet?.settings?.minSettledPredictions || 50 }} lifetime settled predictions and {{ wallet?.settings?.minMonthlySettledPredictions || 5 }} this month.</span></div>
          <div class="td-withdraw-controls td-payout-form"><select v-model="withdrawMethod" aria-label="Withdrawal method"><option value="mobile_money">Mobile Money</option><option value="bank_transfer">Bank Transfer</option></select><input v-model="payout.accountName" placeholder="Account name" aria-label="Account name"/><input v-model="payout.accountNumber" placeholder="Mobile number / account number" aria-label="Account number" inputmode="numeric"/><input v-model="payout.institution" :placeholder="withdrawMethod==='mobile_money'?'Network (e.g. MTN / Telecel)':'Bank name'" :aria-label="withdrawMethod==='mobile_money'?'Mobile money network':'Bank name'"/><button class="btn" :disabled="withdrawSubmitting || Number(wallet?.wallet?.availableBalance||0) < 10 || !payout.accountName || !payout.accountNumber || !payout.institution" @click="requestWithdrawal">{{ withdrawSubmitting ? 'Submitting…' : 'Request withdrawal' }}</button></div>
        </div>
        <div class="td-payout-note"><b>Payout timing</b><span>Withdrawals are processed manually within 1–3 business days after approval.</span></div><div v-if="withdrawMessage" :class="withdrawMessageType==='success'?'success':'error'" class="mt-3">{{ withdrawMessage }}</div>
      </section>

      <section class="td-kpis">
        <div class="td-kpi"><span>Total tips</span><b>{{ tipster?.totalTips || 0 }}</b><small>published selections</small><strong>↗</strong></div>
        <div class="td-kpi"><span>Win rate</span><b>{{ winRate }}%</b><small>{{ tipster?.wins || 0 }} wins · {{ tipster?.losses || 0 }} losses</small><strong>◎</strong></div>
        <div class="td-kpi"><span>Current streak</span><b>{{ tipster?.currentStreak || 0 }}</b><small>consecutive wins</small><strong>↗</strong></div>
        <div class="td-kpi"><span>Pending review</span><b>{{ pendingCount }}</b><small>awaiting admin approval</small><strong>◷</strong></div>
      </section>

      <div class="td-grid">
        <main>
          <section class="pro-panel td-submit" id="submit-prediction">
            <div class="pro-section-head"><div><span class="eyebrow">Publishing desk</span><h2>Submit a prediction</h2><p class="td-head-copy">Create a clear selection for admin review. Published tips become part of your public record.</p></div><span class="td-review-badge">REVIEW REQUIRED</span></div>
            <form v-if="upcomingMatches.length" @submit.prevent="submitPrediction">
              <div class="td-form-section"><div class="td-section-label"><span>01</span><div><b>Match</b><small>Only upcoming scheduled fixtures can be selected.</small></div></div><div class="field"><label>Upcoming fixture</label><select v-model="form.matchId" required @change="selectMatch"><option value="" disabled>Select an upcoming match</option><option v-for="m in upcomingMatches" :key="m._id" :value="m._id">{{ matchLabel(m) }}</option></select></div></div>
              <div class="td-form-section"><div class="td-section-label"><span>02</span><div><b>Selection</b><small>Give members the exact market and price.</small></div></div><div class="td-fields-three"><div class="field"><label>Prediction</label><input v-model="form.prediction" required placeholder="Over 2.5 Goals"/></div><div class="field"><label>Odds</label><input v-model.number="form.odds" type="number" min="1" step=".01" required/></div><div class="field"><label>Confidence</label><select v-model.number="form.confidence"><option :value="90">90% — Very high</option><option :value="80">80% — High</option><option :value="70">70% — Good</option><option :value="60">60% — Moderate</option><option :value="50">50% — Balanced</option></select></div></div></div>
              <div class="td-form-section"><div class="td-section-label"><span>03</span><div><b>Football reasoning</b><small>Explain the factors behind the selection.</small></div></div><div class="field"><label>Analysis</label><textarea v-model="form.analysis" maxlength="3000" placeholder="Form, injuries, home advantage, head-to-head trends, tactical matchup and other relevant evidence…"></textarea><div class="td-counter">{{ form.analysis.length }}/3000</div></div></div>
              <div class="td-submit-foot"><div><b>Before you submit</b><span>Check the fixture, market, odds and reasoning. Your prediction will remain private until approved.</span></div><button class="btn" :disabled="submitting || !form.matchId">{{ submitting ? 'Submitting…' : 'Submit for review →' }}</button></div>
              <div v-if="message" :class="messageType === 'success' ? 'success' : 'error'">{{ message }}</div>
            </form>
            <div v-else class="empty">There are no upcoming scheduled fixtures available right now. The prediction form is hidden until a future match is available.</div>
          </section>

          <section class="pro-panel td-history"><div class="pro-section-head"><div><span class="eyebrow">Publishing pipeline</span><h2>Recent submissions</h2></div><span>{{ predictions.length }} records</span></div><div v-if="predictions.length" class="td-table"><div class="td-table-head"><span>Fixture</span><span>Selection</span><span>Odds</span><span>Status</span></div><div v-for="p in predictions.slice(0,8)" :key="p._id" class="td-table-row"><div><b>{{ p.fixture || 'Football match' }}</b><small>{{ formatDate(p.createdAt) }}</small></div><span>{{ p.prediction }}</span><strong>{{ Number(p.odds || 0).toFixed(2) }}</strong><em :class="'td-status-pill '+p.status">{{ statusLabel(p.status) }}</em></div></div><div v-else class="empty">Your submitted predictions will appear here.</div></section>
        </main>

        <aside class="td-sidebar">
          <section class="pro-panel td-record"><div class="pro-section-head"><div><span class="eyebrow">Performance</span><h2>Your record</h2></div></div><div class="td-record-score"><div><b>{{ winRate }}%</b><span>win rate</span></div><div class="td-ring"><span>{{ tipster?.wins || 0 }}</span><small>WINS</small></div></div><div class="td-progress"><div><span>Wins</span><b>{{ tipster?.wins || 0 }}</b></div><div class="td-track"><i :style="{width: winRate+'%'}"></i></div></div><div class="td-mini-stats"><div><span>Longest streak</span><b>{{ tipster?.longestStreak || 0 }}</b></div><div><span>ROI</span><b>{{ formatPercent(tipster?.roi) }}</b></div><div><span>Profit</span><b>{{ formatProfit(tipster?.profit) }}</b></div></div></section>
          <section class="pro-panel td-profile-card"><span class="eyebrow">Public profile</span><h3>{{ tipster?.username || 'Your profile' }}</h3><p>{{ tipster?.bio || 'Add a clear football bio so members know what your selections specialise in.' }}</p><div class="td-profile-meta"><span>{{ tipster?.expertise || 'Football analysis' }}</span><span>{{ tipster?.country || 'Global' }}</span></div><RouterLink :to="'/tipsters/'+(tipster?.username || '')" class="ghost">View public profile →</RouterLink></section>
          <section class="td-checklist"><span class="eyebrow">Tipster standards</span><h3>Build a trusted record</h3><div><i>✓</i><span>Use precise markets and realistic odds.</span></div><div><i>✓</i><span>Support every selection with football reasoning.</span></div><div><i>✓</i><span>Keep your public record consistent and transparent.</span></div></section>
        </aside>
      </div>
    </template>
    <template v-else>
      <section class="dashboard-welcome"><div><span class="eyebrow">Personal workspace</span><h1>Welcome back, {{auth.user?.name||'there'}}.</h1><p>Track your selections, notifications and football activity from one workspace.</p></div><RouterLink to="/picks" class="btn">Browse latest tips</RouterLink></section>
      <section class="dash-kpis"><div><span>My picks</span><strong>{{picks.length}}</strong><small>tracked selections</small></div><div><span>Open</span><strong>{{openPicks}}</strong><small>awaiting results</small></div><div><span>Won</span><strong>{{wonPicks}}</strong><small>settled wins</small></div><div><span>Notifications</span><strong>{{unread}}</strong><small>unread updates</small></div></section>
      <div class="dashboard-grid"><main><section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">My selections</span><h2>Tracked picks</h2></div><RouterLink to="/history">Public results →</RouterLink></div><div v-if="picks.length" class="my-pick-list"><div v-for="x in picks" :key="x._id" class="my-pick-row"><div><span :class="['result-badge',x.status]">{{x.status}}</span></div><div class="my-pick-fixture"><b>{{x.predictionId?.fixture||'Football match'}}</b><span>{{x.predictionId?.prediction}}</span></div><div><small>Odds</small><b>{{Number(x.predictionId?.odds||0).toFixed(2)}}</b></div><div><small>Stake</small><b>GHS {{Number(x.stake||0).toFixed(2)}}</b></div><button v-if="x.status==='open'" class="ghost" @click="remove(x._id)">Remove</button></div></div><div v-else class="empty">You have no tracked picks yet. <RouterLink to="/picks">Explore the latest predictions →</RouterLink></div></section></main><aside><section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Notifications</span><h2>Activity</h2></div><button class="ghost" @click="markAll">{{unread?'Mark all read':'All read'}}</button></div><div v-if="notifications.length" class="activity-list"><div v-for="n in notifications.slice(0,8)" :key="n._id" :class="['activity-item',{unread:!n.read}]" @click="read(n)"><span class="activity-dot"></span><div><b>{{n.title}}</b><p>{{n.message}}</p><small>{{new Date(n.createdAt).toLocaleString()}}</small></div></div></div><div v-else class="empty compact">No recent notifications.</div></section></aside></div>
    </template>
  </div></div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';import {RouterLink} from 'vue-router';import {useAuth} from '../stores/auth';import {api} from '../services/api';
const auth=useAuth(),picks=ref<any[]>([]),notifications=ref<any[]>([]),unread=ref(0),tipster=ref<any>(null),predictions=ref<any[]>([]),upcomingMatches=ref<any[]>([]),wallet=ref<any>(null),message=ref(''),messageType=ref('success'),submitting=ref(false),withdrawSubmitting=ref(false),withdrawMessage=ref(''),withdrawMessageType=ref('success'),withdrawMethod=ref<'mobile_money'|'bank_transfer'>('mobile_money');const payout=reactive({accountName:'',accountNumber:'',institution:''});const form=reactive<any>({matchId:'',fixture:'',league:'',prediction:'',odds:1.5,confidence:80,analysis:''});const openPicks=computed(()=>picks.value.filter(x=>x.status==='open').length),wonPicks=computed(()=>picks.value.filter(x=>x.status==='won').length),pendingCount=computed(()=>predictions.value.filter(x=>['pending','under_review'].includes(x.status)).length),winRate=computed(()=>{const w=Number(tipster.value?.wins||0),l=Number(tipster.value?.losses||0);return w+l?Math.round(w/(w+l)*100):0});
function money(v:any){const c=wallet.value?.wallet?.currency||'GHS';return `${c} ${Number(v||0).toFixed(2)}`}function initials(v:string){return v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'T'}function formatDate(v:string){return v?new Date(v).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—'}function statusLabel(v:string){return v==='published'?'Published':v==='won'?'Won':v==='lost'?'Lost':v==='void'?'Void':'Pending'}function formatPercent(v:any){return v==null?'—':`${Number(v).toFixed(1)}%`}function formatProfit(v:any){return v==null?'—':Number(v)>=0?`+${Number(v).toFixed(2)}`:Number(v).toFixed(2)}function focusSubmit(){document.getElementById('submit-prediction')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector<HTMLInputElement>('#submit-prediction input')?.focus(),350)}
async function load(){try{const n=await api.get('/me/notifications');notifications.value=n.data||[];unread.value=n.unread||0}catch{}try{picks.value=(await api.get('/me/picks')).data||[]}catch{}if(auth.isTipster)try{const m=await api.get('/matches?status=scheduled&limit=100');upcomingMatches.value=(m.data||[]).filter((x:any)=>new Date(x.kickoff).getTime()>Date.now());if(form.matchId && !upcomingMatches.value.some((x:any)=>String(x._id)===String(form.matchId)))Object.assign(form,{matchId:'',fixture:'',league:''})}catch{upcomingMatches.value=[]}if(auth.isTipster)try{const d=await api.get('/me/tipster');tipster.value=d.data.profile;predictions.value=d.data.predictions||[]}catch{}if(auth.isTipster)try{wallet.value=(await api.get('/me/tipster/wallet')).data}catch{}}
function matchLabel(m:any){const h=m?.homeTeamId?.shortName||m?.homeTeamId?.name||'Home',a=m?.awayTeamId?.shortName||m?.awayTeamId?.name||'Away',dt=m?.kickoff?new Date(m.kickoff).toLocaleString(undefined,{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'TBC';return `${h} vs ${a} · ${dt}`}
function selectMatch(){const m=upcomingMatches.value.find((x:any)=>String(x._id)===String(form.matchId));if(m){form.fixture=`${m.homeTeamId?.name||'Home'} vs ${m.awayTeamId?.name||'Away'}`;form.league=m.leagueId?.name||''}}
async function read(n:any){if(!n.read){try{await api.patch(`/me/notifications/${n._id}/read`,{});n.read=true;unread.value=Math.max(0,unread.value-1)}catch{}}}async function markAll(){try{await api.patch('/me/notifications/read-all',{});notifications.value.forEach(n=>n.read=true);unread.value=0}catch{}}async function remove(id:string){try{await api.delete(`/me/picks/${id}`);await load()}catch{}}async function requestWithdrawal(){if(Number(wallet.value?.wallet?.availableBalance||0)<10){withdrawMessage.value='Minimum withdrawal is 10.00 in your wallet currency.';withdrawMessageType.value='error';return}if(!payout.accountName||!payout.accountNumber||!payout.institution){withdrawMessage.value='Enter your payout account details first.';withdrawMessageType.value='error';return}withdrawSubmitting.value=true;withdrawMessage.value='';try{const d=await api.post('/me/tipster/wallet/withdraw',{amount:Number(wallet.value.wallet.availableBalance),method:withdrawMethod.value,accountName:payout.accountName,accountNumber:payout.accountNumber,institution:payout.institution});withdrawMessage.value=d.message||'Withdrawal request submitted. Approved payouts are processed within 1–3 business days.';withdrawMessageType.value='success';wallet.value=(await api.get('/me/tipster/wallet')).data}catch(e:any){withdrawMessage.value=e?.message||'Unable to submit withdrawal request.';withdrawMessageType.value='error'}finally{withdrawSubmitting.value=false}}
async function submitPrediction(){const m=upcomingMatches.value.find((x:any)=>String(x._id)===String(form.matchId));if(!m || new Date(m.kickoff).getTime()<=Date.now()){message.value='This fixture is no longer upcoming. Please select another match.';messageType.value='error';await load();return}submitting.value=true;message.value='';try{const d=await api.post('/me/tipster/predictions',{matchId:form.matchId,prediction:form.prediction,odds:form.odds,confidence:form.confidence,analysis:form.analysis});message.value=d.message||'Prediction submitted for admin review';messageType.value='success';Object.assign(form,{matchId:'',fixture:'',league:'',prediction:'',odds:1.5,confidence:80,analysis:''});await load()}catch(e:any){message.value=e?.message||'Unable to submit prediction.';messageType.value='error'}finally{submitting.value=false}}onMounted(load);
</script>
