<template>
  <div class="info-page page-animate"><div class="wrap info-wrap">
    <section class="info-hero"><span class="eyebrow">BraTipsters</span><h1>{{ title }}</h1><p>{{ intro }}</p></section>
    <div class="info-layout"><aside class="info-nav"><b>Help & information</b><RouterLink to="/how-to-use">How to use BraTipsters</RouterLink><RouterLink to="/whats-new">What's New</RouterLink><RouterLink to="/faq">Frequently asked questions</RouterLink><RouterLink to="/tipster-rankings">Monthly tipster rankings</RouterLink><RouterLink to="/about">About BraTipsters</RouterLink><RouterLink to="/betting-guides">Betting Guides</RouterLink><RouterLink to="/glossary">Glossary</RouterLink></aside><article class="info-content"><slot><section v-for="s in sections" :key="s.heading" class="info-section"><h2>{{s.heading}}</h2><p v-for="p in s.paragraphs||[]" :key="p">{{p}}</p><ul v-if="s.items"><li v-for="i in s.items" :key="i">{{i}}</li></ul><div v-if="s.note" class="info-note"><span>{{s.noteLabel || 'Tip'}}</span><p>{{s.note}}</p></div></section></slot></article></div>
  </div></div>
</template>
<script setup lang="ts">import {computed} from 'vue';import {RouterLink} from 'vue-router';const props=defineProps<{title:string;intro:string;sections?:{heading:string;paragraphs?:string[];items?:string[];note?:string;noteLabel?:string}[]}>();const content:Record<string,{heading:string;paragraphs?:string[];items?:string[];note?:string;noteLabel?:string}[]>= {
'How to use BraTipsters':[
  {heading:'1. Find a match',paragraphs:['Open Matches to browse today\u2019s and upcoming fixtures across supported leagues. Use the league and date filters to narrow things down, then tap a fixture to open its Match Centre.','Inside Match Centre you can inspect team form, head-to-head history, league standings, live/latest odds and available statistics before deciding anything.'],items:['League & date filters — narrow fixtures fast','Live scores for matches already underway','Odds shown per market, updated as prices move']},
  {heading:'2. Explore tips',paragraphs:['Open Tips or Bet of the Day to see published predictions, along with the market, the odds at the time of posting, and the tipster\u2019s confidence or reasoning where they\u2019ve included it.','You can also open any tipster\u2019s profile directly from a tip to see their full track record before deciding whether to follow that selection.'],note:'A tip\u2019s odds can move after it\u2019s published. Always check the current price on your bookmaker before staking.',noteLabel:'Good to know'},
  {heading:'3. Read the tipster stats',paragraphs:['Every tipster card shows a small strip of green and red boxes — green is a settled win, red is a settled loss — giving you an instant read on recent form alongside the full "wins · losses" count.','Win rate is wins divided by total settled tips. ROI (Return on Investment) shows profit relative to stake, which matters more than win rate alone: a tipster can win often at low odds and still have weak ROI, or win less often at higher odds and have strong ROI.'],items:['Win rate — % of settled tips that won','ROI — profit relative to stake, the clearest long-term signal','Current streak — consecutive wins right now','Longest streak — their best run on record']},
  {heading:'4. Compare tipsters',paragraphs:['Use Tipsters for long-term, all-time performance, and Monthly Tipster Rankings to see who\u2019s performing best in the current calendar month specifically — useful because form changes.','Don\u2019t judge on a single result. Look at volume (how many tips they\u2019ve actually settled), consistency over time, and ROI together, not any one number in isolation.']},
  {heading:'5. Understand results & Dropping Odds',paragraphs:['Settled predictions are marked Won, Lost or Void. Results are tracked automatically once match result data is available — see the Results Tracking Policy for exactly how that works.','Dropping Odds tracks selections whose price is shortening (falling), which can indicate where market money is moving. It\u2019s a signal to research further, not a tip in itself.']},
  {heading:'6. Follow tipsters & get notified',paragraphs:['Sign in and follow any approved tipster from their profile to build a personalised feed and receive notifications when they publish something new — handled from the bell icon in the top navigation.']},
  {heading:'7. Use Premium research',paragraphs:['Premium unlocks additional content and research features for subscribers, billed through Stripe. What\u2019s included depends on your active plan — see Premium features for the current breakdown.']},
  {heading:'8. Follow responsibly',paragraphs:['BraTipsters provides information and analysis, not guaranteed outcomes — no tipster, however consistent, wins every time. Set your own limits and never stake money you cannot afford to lose.'],note:'If betting stops being fun or feels hard to control, BeGambleAware and similar local support organisations can help. 18+ only.',noteLabel:'Play safe'}
],
'What’s New':[{heading:'Automatic Bet of the Day',paragraphs:['Bet of the Day is now selected and published automatically from upcoming fixtures and available markets. There is no admin approval step before a selection appears publicly.']},{heading:'More than Double Chance',paragraphs:['The automatic selector is no longer restricted to Double Chance. It can consider 1X2, BTTS, Over/Under, corners and other supported markets, including higher-odds selections when the available data supports a plausible outcome.']},{heading:'Prediction Trends on the homepage',paragraphs:['The homepage now highlights the most active tracked prediction markets with their settled volume, win rate and profit, helping you spot what has been trending across published tips.']},{heading:'Better navigation & readability',paragraphs:['How to Use, What’s New and FAQ are easier to reach from the homepage, while headings and key information have been made more prominent.']}],
'Frequently Asked Questions':[{heading:'Are BraTipsters tips guaranteed?',paragraphs:['No. Football is unpredictable and no tip is guaranteed. Past performance does not guarantee future results.']},{heading:'How are tipster results tracked?',paragraphs:['Published predictions are settled against available match results and recorded as Won, Lost or Void when the result can be determined reliably.']},{heading:'What is a void prediction?',paragraphs:['A prediction can be void when the market cannot be settled reliably from the available result information or when the relevant outcome is ambiguous.']},{heading:'How does Premium work?',paragraphs:['Premium is a subscription service processed through Stripe. Your account receives access according to the active plan and subscription status.']},{heading:'Can I follow a tipster?',paragraphs:['Yes. Signed-in users can follow approved tipsters and receive supported notifications when new tips are published.']},{heading:'Can I become a tipster?',paragraphs:['Yes. Use Become a Tipster to submit an application. Applications are reviewed before tipster access is activated.']}],
'About BraTipsters':[{heading:'Our purpose',paragraphs:['BraTipsters brings football predictions, match research, tipster performance and results tracking into one focused platform.']},{heading:'Transparent performance',paragraphs:['We aim to make performance easier to inspect by showing tracked tips, results, profit, ROI, streaks and monthly rankings rather than relying only on promotional claims.']},{heading:'Independent tipster profiles',paragraphs:['Approved tipsters publish their own selections and analysis. BraTipsters provides the platform, tracking and review framework.']}],
'Editorial Policy':[{heading:'Editorial standards',paragraphs:['BraTipsters content is designed to be clear, football-focused and distinguish opinion or analysis from verified match information.']},{heading:'Tipster content',paragraphs:['Tips and analysis are manually written and reviewed before publication where applicable. Review does not mean a prediction is guaranteed or endorsed as certain to win.']},{heading:'Corrections',paragraphs:['If an important factual or tracking error is identified, BraTipsters may correct the record and preserve the appropriate result history.']}],
'Results Tracking Policy':[{heading:'How settlement works',paragraphs:['BraTipsters uses available fixture and result information to settle supported prediction markets. Clear outcomes are recorded as Won or Lost; outcomes that cannot be reliably determined may be marked Void.']},{heading:'Timing',paragraphs:['Results can be updated after the match as provider data becomes available. A displayed result is not a promise of a bookmaker settlement.']},{heading:'Historical record',paragraphs:['Tracked results are intended to provide a consistent performance record. Users should review the underlying prediction and match information before drawing conclusions.']}],
'Betting Guides':[{heading:'Core football markets',items:['Match result: Home, Draw or Away.','Double Chance: 1X, X2 or 12.','Both Teams To Score (BTTS).','Over/Under goals, including Over 2.5.','Corners and other supported markets.']},{heading:'Reading odds',paragraphs:['Odds express the price attached to an outcome. Compare the odds with your own assessment of probability and remember that higher odds generally imply lower market probability, not a better bet.']},{heading:'Research before deciding',paragraphs:['Use form, H2H, xGoals, standings, gameplay statistics and price movement as context rather than as guarantees.']}],
'Betting Glossary':[{heading:'BTTS',paragraphs:['Both Teams To Score — a market asking whether both teams will score at least once.']},{heading:'xG',paragraphs:['Expected Goals — a model-based estimate of the quality and likelihood of scoring chances.']},{heading:'ROI',paragraphs:['Return on Investment — profit expressed relative to the amount used as the reference stake or investment.']},{heading:'Odds',paragraphs:['The price attached to a betting outcome.']},{heading:'Void',paragraphs:['A prediction whose outcome is not counted as a win or loss for tracked performance.']}],
'BraTipsters Blog':[{heading:'What you will find here',paragraphs:['Football research ideas, product updates, tipster education and explanations of the tools available on BraTipsters.']},{heading:'Publishing approach',paragraphs:['Blog content should complement the live product and be clearly dated when the information is time-sensitive.']}],
'Terms of Use':[{heading:'Use of the service',paragraphs:['By using BraTipsters, you agree to use the service lawfully and responsibly and to respect account, subscription and content rules.']},{heading:'Information only',paragraphs:['Predictions, statistics and analysis are provided for informational purposes and do not constitute a guarantee of any outcome.']},{heading:'Accounts and subscriptions',paragraphs:['Users are responsible for their account credentials and for maintaining accurate account information. Subscription billing is handled through Stripe according to the applicable plan terms.']}],
'Privacy & Cookie Policy':[{heading:'Information we collect',paragraphs:['BraTipsters may process account, subscription, preference and service-usage information needed to operate the platform.']},{heading:'Cookies and local storage',paragraphs:['The public application may use browser storage for authentication state and performance-related caching.']},{heading:'Third parties',paragraphs:['Payment and sports-data services may process information necessary to provide their respective services.']}],
'Contact BraTipsters':[{heading:'Support',paragraphs:['For account, subscription, tipster application or results-tracking questions, contact the BraTipsters support team through the official contact channel provided by the site.']},{heading:'Corrections and feedback',paragraphs:['When reporting a tracking issue, include the relevant match, prediction and date so the team can investigate efficiently.']}]};const sections=computed(()=>props.sections||content[props.title]||[{heading:'BraTipsters information',paragraphs:['This page is part of the BraTipsters information centre.']}]);</script>
