<template>
  <div class="info-page page-animate"><div class="wrap info-wrap">
    <section class="info-hero"><span class="eyebrow">BraTipsters</span><h1>{{ title }}</h1><p>{{ intro }}</p></section>
    <div class="info-layout"><aside class="info-nav"><b>Help & information</b><RouterLink to="/how-to-use">How to use BraTipsters</RouterLink><RouterLink to="/faq">Frequently asked questions</RouterLink><RouterLink to="/tipster-rankings">Monthly tipster rankings</RouterLink><RouterLink to="/about">About BraTipsters</RouterLink><RouterLink to="/betting-guides">Betting Guides</RouterLink><RouterLink to="/glossary">Glossary</RouterLink></aside><article class="info-content"><slot><section v-for="s in sections" :key="s.heading" class="info-section"><h2>{{s.heading}}</h2><p v-for="p in s.paragraphs||[]" :key="p">{{p}}</p><ul v-if="s.items"><li v-for="i in s.items" :key="i">{{i}}</li></ul></section></slot></article></div>
  </div></div>
</template>
<script setup lang="ts">import {computed} from 'vue';import {RouterLink} from 'vue-router';const props=defineProps<{title:string;intro:string;sections?:{heading:string;paragraphs?:string[];items?:string[]}[]}>();const content:Record<string,{heading:string;paragraphs?:string[];items?:string[]}[]>= {
'How to use BraTipsters':[{heading:'1. Find a match',paragraphs:['Open Matches to browse upcoming fixtures, leagues and match research. Use Match Centre to inspect available form, odds, standings, H2H and statistics.']},{heading:'2. Explore tips',paragraphs:['Open Tips or a tipster profile to see published predictions, odds, confidence and reasoning where available.']},{heading:'3. Compare tipsters',paragraphs:['Use Tipsters for long-term performance and Monthly Tipster Rankings for calendar-month results. Look beyond a single win: volume, consistency, ROI and tracked history matter.']},{heading:'4. Understand results',paragraphs:['Settled predictions are marked Won, Lost or Void. Results are tracked automatically when sufficient match result data is available.']},{heading:'5. Use Premium research',paragraphs:['Premium unlocks additional content and research features for subscribers. Availability depends on your active subscription and the feature set offered by BraTipsters.']},{heading:'6. Follow responsibly',paragraphs:['BraTipsters provides information and analysis, not guaranteed outcomes. Set your own limits and never stake money you cannot afford to lose.']}],
'Frequently Asked Questions':[{heading:'Are BraTipsters tips guaranteed?',paragraphs:['No. Football is unpredictable and no tip is guaranteed. Past performance does not guarantee future results.']},{heading:'How are tipster results tracked?',paragraphs:['Published predictions are settled against available match results and recorded as Won, Lost or Void when the result can be determined reliably.']},{heading:'What is a void prediction?',paragraphs:['A prediction can be void when the market cannot be settled reliably from the available result information or when the relevant outcome is ambiguous.']},{heading:'How does Premium work?',paragraphs:['Premium is a subscription service processed through Stripe. Your account receives access according to the active plan and subscription status.']},{heading:'Can I follow a tipster?',paragraphs:['Yes. Signed-in users can follow approved tipsters and receive supported notifications when new tips are published.']},{heading:'Can I become a tipster?',paragraphs:['Yes. Use Become a Tipster to submit an application. Applications are reviewed before tipster access is activated.']}],
'About BraTipsters':[{heading:'Our purpose',paragraphs:['BraTipsters brings football predictions, match research, tipster performance and results tracking into one focused platform.']},{heading:'Transparent performance',paragraphs:['We aim to make performance easier to inspect by showing tracked tips, results, profit, ROI, streaks and monthly rankings rather than relying only on promotional claims.']},{heading:'Independent tipster profiles',paragraphs:['Approved tipsters publish their own selections and analysis. BraTipsters provides the platform, tracking and review framework.']}],
'Editorial Policy':[{heading:'Editorial standards',paragraphs:['BraTipsters content is designed to be clear, football-focused and distinguish opinion or analysis from verified match information.']},{heading:'Tipster content',paragraphs:['Tips and analysis are manually written and reviewed before publication where applicable. Review does not mean a prediction is guaranteed or endorsed as certain to win.']},{heading:'Corrections',paragraphs:['If an important factual or tracking error is identified, BraTipsters may correct the record and preserve the appropriate result history.']}],
'Results Tracking Policy':[{heading:'How settlement works',paragraphs:['BraTipsters uses available fixture and result information to settle supported prediction markets. Clear outcomes are recorded as Won or Lost; outcomes that cannot be reliably determined may be marked Void.']},{heading:'Timing',paragraphs:['Results can be updated after the match as provider data becomes available. A displayed result is not a promise of a bookmaker settlement.']},{heading:'Historical record',paragraphs:['Tracked results are intended to provide a consistent performance record. Users should review the underlying prediction and match information before drawing conclusions.']}],
'Betting Guides':[{heading:'Core football markets',items:['Match result: Home, Draw or Away.','Double Chance: 1X, X2 or 12.','Both Teams To Score (BTTS).','Over/Under goals, including Over 2.5.','Corners and other supported markets.']},{heading:'Reading odds',paragraphs:['Odds express the price attached to an outcome. Compare the odds with your own assessment of probability and remember that higher odds generally imply lower market probability, not a better bet.']},{heading:'Research before deciding',paragraphs:['Use form, H2H, xGoals, standings, gameplay statistics and price movement as context rather than as guarantees.']}],
'Betting Glossary':[{heading:'BTTS',paragraphs:['Both Teams To Score — a market asking whether both teams will score at least once.']},{heading:'xG',paragraphs:['Expected Goals — a model-based estimate of the quality and likelihood of scoring chances.']},{heading:'ROI',paragraphs:['Return on Investment — profit expressed relative to the amount used as the reference stake or investment.']},{heading:'Odds',paragraphs:['The price attached to a betting outcome.']},{heading:'Void',paragraphs:['A prediction whose outcome is not counted as a win or loss for tracked performance.']}],
'BraTipsters Blog':[{heading:'What you will find here',paragraphs:['Football research ideas, product updates, tipster education and explanations of the tools available on BraTipsters.']},{heading:'Publishing approach',paragraphs:['Blog content should complement the live product and be clearly dated when the information is time-sensitive.']}],
'Terms of Use':[{heading:'Use of the service',paragraphs:['By using BraTipsters, you agree to use the service lawfully and responsibly and to respect account, subscription and content rules.']},{heading:'Information only',paragraphs:['Predictions, statistics and analysis are provided for informational purposes and do not constitute a guarantee of any outcome.']},{heading:'Accounts and subscriptions',paragraphs:['Users are responsible for their account credentials and for maintaining accurate account information. Subscription billing is handled through Stripe according to the applicable plan terms.']}],
'Privacy & Cookie Policy':[{heading:'Information we collect',paragraphs:['BraTipsters may process account, subscription, preference and service-usage information needed to operate the platform.']},{heading:'Cookies and local storage',paragraphs:['The public application may use browser storage for authentication state and performance-related caching.']},{heading:'Third parties',paragraphs:['Payment and sports-data services may process information necessary to provide their respective services.']}],
'Contact BraTipsters':[{heading:'Support',paragraphs:['For account, subscription, tipster application or results-tracking questions, contact the BraTipsters support team through the official contact channel provided by the site.']},{heading:'Corrections and feedback',paragraphs:['When reporting a tracking issue, include the relevant match, prediction and date so the team can investigate efficiently.']}]};const sections=computed(()=>props.sections||content[props.title]||[{heading:'BraTipsters information',paragraphs:['This page is part of the BraTipsters information centre.']}]);</script>
