<template>
<div class="pro-page member-dashboard page-animate"><div class="dashboard-shell member-shell">
<aside class="dashboard-nav member-nav"><div class="dashboard-brand"><span>BRATIPSTERS</span><b>MEMBER HUB</b></div><RouterLink to="/dashboard">Overview</RouterLink><a href="#premium">Premium Tips</a><a href="#saved">Saved Predictions</a><a href="#following">My Tipsters</a><RouterLink to="/history">Prediction History</RouterLink><RouterLink to="/subscription">Premium Subscription</RouterLink><a href="#account">Account Settings</a><RouterLink to="/">← Back to site</RouterLink></aside>
<main class="dashboard-content"><section class="member-hero pro-panel"><div class="member-welcome"><div class="member-avatar">{{ initials(auth.user?.name||'M') }}</div><div><span class="eyebrow">Member workspace</span><h1>Welcome back, {{ auth.user?.name||'Member' }}</h1><p>Your personal football hub for Premium tips, saved predictions and the tipsters you follow.</p></div></div><RouterLink to="/picks" class="btn">Explore predictions</RouterLink></section>
<section class="member-kpis"><div class="member-kpi"><span>Premium</span><b>{{ premiumActive?'Active':'Not active' }}</b><small>{{ premiumEnd?'Renews '+formatDate(premiumEnd):'Unlock Premium predictions' }}</small></div><div class="member-kpi"><span>Saved picks</span><b>{{ picks.length }}</b><small>tracked in your account</small></div><div class="member-kpi"><span>Following</span><b>{{ follows.length }}</b><small>tipsters you follow</small></div><div class="member-kpi"><span>Winning picks</span><b>{{ wonPicks }}</b><small>results tracked</small></div></section>
<section id="premium" class="member-premium pro-panel"><div><span class="eyebrow">Premium access</span><h2>{{ premiumActive?'Your Premium membership':'Upgrade your football research' }}</h2><p>{{ premiumActive?'Your Premium access is active on this same member account. Explore Premium predictions and keep your saved picks in one place.':'Create a Premium subscription to access Premium predictions. You do not need a tipster account.' }}</p></div><RouterLink to="/subscription" class="btn">{{ premiumActive?'Manage Premium':'View Premium plans' }}</RouterLink></section>
<div class="member-content-grid"><section id="saved" class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Your activity</span><h2>Saved predictions</h2></div><RouterLink to="/picks">Browse picks →</RouterLink></div><div v-if="picks.length" class="member-list"><RouterLink v-for="p in picks.slice(0,8)" :key="p._id" :to="p.predictionId?`/predictions/${p.predictionId._id}`:'/picks'" class="member-row"><span :class="['result-badge',p.status]">{{p.status}}</span><div><b>{{p.predictionId?.fixture||'Football match'}}</b><small>{{p.predictionId?.prediction||'Saved prediction'}}</small></div><strong>{{ odds(p.predictionId?.odds) }}</strong></RouterLink></div><EmptyState v-else title="No saved predictions" message="Save predictions from the Picks page and they will appear here." ><template #action><RouterLink to="/picks" class="btn">Explore picks</RouterLink></template></EmptyState></section>
<section id="following" class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Your tipsters</span><h2>Following</h2></div><RouterLink to="/tipsters">Discover →</RouterLink></div><div v-if="follows.length" class="member-follow-list"><RouterLink v-for="f in follows.slice(0,8)" :key="f._id" :to="f.tipsterId?`/tipsters/${encodeURIComponent(f.tipsterId.name)}`:'/tipsters'" class="follow-row"><div class="follow-avatar">{{initials(f.tipsterId?.name||'T')}}</div><div><b>{{f.tipsterId?.name||'Tipster'}}</b><small>Followed tipster</small></div><span>View →</span></RouterLink></div><EmptyState v-else title="You are not following anyone yet" message="Discover tipsters and follow the analysts whose work you want to track."><template #action><RouterLink to="/tipsters" class="btn">Browse tipsters</RouterLink></template></EmptyState></section></div>
<section id="account" class="pro-panel member-account"><div><span class="eyebrow">Account settings</span><h2>Your member account</h2><div class="member-settings"><div class="field"><label>Full name</label><input v-model="accountName" maxlength="100"/></div><p>{{auth.user?.email}}</p></div><small>Premium is attached to this account independently of your role. If you later become an approved tipster, the same account can remain Premium.</small></div><div class="account-actions"><button class="btn" :disabled="accountSaving" @click="saveAccount">{{accountSaving?'Saving…':'Save account'}}</button><RouterLink to="/subscription" class="ghost">Subscription</RouterLink><RouterLink to="/history" class="ghost">Prediction history</RouterLink></div></section>
</main></div></div>
</template>
<script setup lang="ts">import{computed,onMounted,ref}from'vue';import{RouterLink}from'vue-router';import{useAuth}from'../stores/auth';import{api}from'../services/api';import EmptyState from'../components/EmptyState.vue';const auth=useAuth();const accountName=ref(auth.user?.name||''),accountSaving=ref(false);const picks=ref<any[]>([]),follows=ref<any[]>([]),premiumActive=ref(false),premiumEnd=ref<any>(null);const wonPicks=computed(()=>picks.value.filter(x=>x.status==='won').length);function initials(v:string){return v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'M'}function formatDate(v:any){return v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):''}function odds(v:any){return Number(v||0).toFixed(2)}async function saveAccount(){accountSaving.value=true;try{const d=await api.patch('/me/profile',{name:accountName.value});auth.user=d.user}catch{}finally{accountSaving.value=false}}async function load(){try{picks.value=(await api.get('/me/picks')).data||[]}catch{}try{follows.value=(await api.get('/me/follows')).data||[]}catch{}try{const d=await api.get('/billing/me');premiumActive.value=Boolean(d.data?.active&&d.data?.subscription?.plan==='premium');premiumEnd.value=d.data?.subscription?.currentPeriodEnd||null}catch{}}onMounted(load)</script>
