<template>
  <div class="pro-page page-animate">
    <div class="wrap">
      <section class="football-hero page-hero-compact"><div><span class="eyebrow">Featured football tips</span><h1>Latest predictions</h1><p>Explore published picks, compare odds and open the full match research behind every selection.</p></div><RouterLink to="/tipsters" class="hero-action">Compare tipsters →</RouterLink></section>
      <section class="signal-strip"><div><span class="pulse-dot"></span><b>Prediction feed live</b><small>New published tips appear here automatically.</small></div><div><b>{{filtered.length}}</b><small>visible picks</small></div><div><b>{{wonCount}}</b><small>settled wins</small></div><RouterLink to="/history">View track record →</RouterLink></section>
      <div class="research-toolbar"><div class="segmented"><button :class="{active:horizon==='daily'}" @click="horizon='daily';load()">Today</button><button :class="{active:horizon==='weekly'}" @click="horizon='weekly';load()">This Week</button><button :class="{active:horizon===''}" @click="horizon='';load()">All</button></div><div class="search-field"><span>⌕</span><input v-model="search" placeholder="Search team, league or tipster"/></div><div class="segmented"><button v-for="s in statuses" :key="s.v" :class="{active:status===s.v}" @click="status=s.v">{{s.l}}</button></div></div>
      <div v-if="loading" class="grid3"><div v-for="n in 6" :key="n" class="tip-skeleton"></div></div>
      <div v-else-if="error" class="pro-panel error">{{error}} <button class="ghost" @click="load">Try again</button></div>
      <div v-else class="grid3"><PickCard v-for="p in filtered" :key="p._id" :pick="p" @play="play"/><EmptyState v-if="!filtered.length" title="No predictions found" message="No published predictions match your current filters. Try another day, status or search term." icon="⌕"><template #action><button class="ghost" type="button" @click="search='';status=''">Clear filters</button></template></EmptyState></div>
      <section class="premium-research"><div class="premium-icon">★</div><div><span class="eyebrow">Premium research</span><h2>Go deeper than the pick</h2><p>Unlock the full BraTipsters research experience, market context and premium prediction content.</p></div><RouterLink to="/subscription" class="btn">Explore Premium</RouterLink></section>
    </div>
  </div>
</template>
<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {RouterLink,useRouter,useRoute} from 'vue-router';import {api} from '../services/api';import PickCard from '../components/PickCard.vue';import EmptyState from '../components/EmptyState.vue';
const data=ref<any[]>([]),search=ref(''),status=ref(''),horizon=ref(''),loading=ref(true),error=ref(''),router=useRouter(),route=useRoute();const statuses=[{v:'',l:'All'},{v:'published',l:'Published'},{v:'won',l:'Won'},{v:'lost',l:'Lost'}];
const filtered=computed(()=>data.value.filter(p=>(!status.value||p.status===status.value)&&(!search.value||`${p.fixture||''} ${p.league||''} ${p.tipsterId?.name||''} ${p.matchId?.homeTeamId?.name||''} ${p.matchId?.awayTeamId?.name||''}`.toLowerCase().includes(search.value.toLowerCase()))));const wonCount=computed(()=>data.value.filter(p=>p.status==='won').length);function play(){router.push('/login')};async function load(){loading.value=true;error.value='';try{const base=horizon.value?`/predictions?limit=50&horizon=${horizon.value}`:'/predictions?limit=50';const first=await api.get(base);data.value=first.data||[];const pages=Math.min(Number(first.pagination?.pages||1),10);if(pages>1){const rest=await Promise.all(Array.from({length:pages-1},(_,i)=>api.get(horizon.value?`/predictions?limit=50&horizon=${horizon.value}&page=${i+2}`:`/predictions?limit=50&page=${i+2}`)).map(x=>x.catch(()=>({data:[]}))));data.value=[...data.value,...rest.flatMap((x:any)=>x.data||[])];}}catch(e:any){error.value=e?.message||'Unable to load predictions.'}finally{loading.value=false}}onMounted(()=>{const h=String(route.query.horizon||'');if(['daily','weekly'].includes(h))horizon.value=h;load()});
</script>
