<template>
  <div class="pro-page page-animate"><div class="wrap">
    <div v-if="loading" class="pro-panel detail-loading">Loading prediction intelligence…</div>
    <EmptyState v-else-if="!item" title="Prediction not found" message="This prediction may have been removed or is no longer available." icon="⌕"><template #action><RouterLink to="/predictions" class="btn">Browse predictions</RouterLink></template></EmptyState>
    <template v-else>
      <section v-if="item.locked" class="pro-panel premium-locked-detail"><RouterLink to="/picks" class="back-soft">← Latest picks</RouterLink><span class="premium-badge">PREMIUM TIP</span><h1>Selection locked</h1><p>{{item.fixture||'Football fixture'}}</p><p class="muted">Subscribe to reveal this selection.</p><RouterLink to="/subscription" class="btn">View plans</RouterLink><button class="ghost detail-share-button" type="button" @click="sharePrediction">Share prediction</button></section>
      <section v-else class="prediction-hero"><div><RouterLink to="/picks" class="back-soft">← Latest picks</RouterLink><span class="eyebrow">Prediction analysis</span><h1>{{item.prediction}}</h1><p>{{item.fixture||'Football fixture'}}</p></div><div class="prediction-result"><span :class="['result-badge large',item.status]">{{String(item.status).toUpperCase()}}</span><strong v-if="item.matchId?.status==='finished'">FINAL {{item.matchId?.homeScore}} : {{item.matchId?.awayScore}}</strong><small v-else>{{String(item.matchId?.status||'scheduled').toUpperCase()}}</small><button class="detail-share-button detail-share-button-dark" type="button" @click="sharePrediction">Share</button></div></section>
      <div v-if="!item.locked" class="prediction-grid"><main><section class="pro-panel prediction-match"><div class="prediction-teams"><div><TeamLogo :src="item.matchId?.homeTeamId?.logo" :name="item.matchId?.homeTeamId?.name" size="lg"/><b>{{item.matchId?.homeTeamId?.name||'Home'}}</b></div><span>VS</span><div><TeamLogo :src="item.matchId?.awayTeamId?.logo" :name="item.matchId?.awayTeamId?.name" size="lg"/><b>{{item.matchId?.awayTeamId?.name||'Away'}}</b></div></div><div class="prediction-kpi-row"><div><span>Match status</span><strong>{{item.matchId?.status==='finished'?'Finished':item.matchId?.status==='live'?'Live':'Scheduled'}}</strong></div><div><span>Odds</span><strong>{{formatOdds(item.odds)}}</strong></div><div><span>Confidence</span><strong>{{item.confidence||'—'}}%</strong></div><div><span>Market</span><strong>{{item.prediction}}</strong></div></div></section><section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Analyst reasoning</span><h2>Why this pick?</h2></div></div><p class="analysis-copy">{{item.analysis||'No extended analysis was published for this prediction.'}}</p></section></main><aside><section class="pro-panel"><span class="eyebrow">Tipster</span><h2>@{{item.tipsterId?.name||'BraTipsters tipster'}}</h2><p class="muted">Review this contributor's broader performance before following a single prediction.</p><RouterLink to="/tipsters" class="btn btn-wide">Explore tipsters</RouterLink></section><section class="pro-panel"><span class="eyebrow">Match research</span><h3>Go beyond the selection</h3><p class="muted">View odds, xG, form, events, H2H and standings in the Football Match Centre.</p><RouterLink v-if="item.matchId?._id" :to="`/matches/${item.matchId._id}`" class="ghost btn-wide">Open Match Centre</RouterLink></section></aside></div>
    </template>
  </div></div>
</template>
<script setup lang="ts">import {onMounted,ref} from 'vue';import {RouterLink,useRoute} from 'vue-router';import {api} from '../services/api';import TeamLogo from '../components/TeamLogo.vue';import {useToast} from '../composables/feedback';import EmptyState from '../components/EmptyState.vue';import {formatOdds} from '../utils/formatters';import {shareOrCopy} from '../utils/share';const route=useRoute(),item=ref<any>(null),loading=ref(true),{show:toast}=useToast();async function sharePrediction(){if(!item.value)return;try{const locked=Boolean(item.value.locked);const selection=locked?'Premium prediction':item.value.prediction||'Prediction';const odds=!locked&&item.value.odds?` at odds ${formatOdds(item.value.odds)}`:'';const result=await shareOrCopy({title:`BraTipsters prediction: ${selection}`,text:`${item.value.fixture||'Football fixture'}: ${selection}${odds}`,url:`/predictions/${route.params.id}`});if(result==='copied')toast('Prediction link copied to your clipboard.','success','Share prediction')}catch{toast('This prediction link could not be shared.','error','Share prediction')}}onMounted(async()=>{try{item.value=(await api.get(`/predictions/${route.params.id}`)).data}catch{toast('This prediction could not be loaded. Please try again.','error','Prediction')}finally{loading.value=false}});</script>

<style scoped>.premium-locked-detail{margin:30px 0;padding:40px}.premium-locked-detail .detail-share-button{display:block;margin-top:10px;width:max-content}.prediction-result{display:flex;flex-direction:column;align-items:flex-end;gap:6px}.prediction-result strong{font-size:13px;color:#fff}.prediction-result small{font-size:8px;color:#b9c5d7;font-weight:900}.detail-share-button{border:1px solid #dfe5ed;border-radius:10px;cursor:pointer;font-size:12px;font-weight:900;padding:10px 13px}.detail-share-button-dark{margin-top:8px;background:rgba(255,255,255,.1);border-color:rgba(255,255,255,.18);color:#fff}.detail-share-button-dark:hover{background:#fff;color:#17243b}.prediction-kpi-row{grid-template-columns:repeat(4,1fr)}@media(max-width:760px){.premium-locked-detail .detail-share-button{width:100%}.prediction-result strong{font-size:11px}.prediction-kpi-row{grid-template-columns:repeat(2,1fr)}} </style>
