<template>
  <div class="pro-page page-animate"><div class="wrap">
    <div v-if="loading" class="pro-panel detail-loading">Loading prediction intelligence…</div>
    <div v-else-if="!item" class="pro-panel empty">Prediction not found.</div>
    <template v-else>
      <section class="prediction-hero"><div><RouterLink to="/picks" class="back-soft">← Latest picks</RouterLink><span class="eyebrow">Prediction analysis</span><h1>{{item.prediction}}</h1><p>{{item.fixture||'Football fixture'}}</p></div><span :class="['result-badge large',item.status]">{{item.status}}</span></section>
      <div class="prediction-grid"><main><section class="pro-panel prediction-match"><div class="prediction-teams"><div><TeamLogo :src="item.matchId?.homeTeamId?.logo" :name="item.matchId?.homeTeamId?.name" size="lg"/><b>{{item.matchId?.homeTeamId?.name||'Home'}}</b></div><span>VS</span><div><TeamLogo :src="item.matchId?.awayTeamId?.logo" :name="item.matchId?.awayTeamId?.name" size="lg"/><b>{{item.matchId?.awayTeamId?.name||'Away'}}</b></div></div><div class="prediction-kpi-row"><div><span>Odds</span><strong>{{Number(item.odds||0).toFixed(2)}}</strong></div><div><span>Confidence</span><strong>{{item.confidence||'—'}}%</strong></div><div><span>Market</span><strong>{{item.prediction}}</strong></div></div></section><section class="pro-panel"><div class="pro-section-head"><div><span class="eyebrow">Analyst reasoning</span><h2>Why this pick?</h2></div></div><p class="analysis-copy">{{item.analysis||'No extended analysis was published for this prediction.'}}</p></section></main><aside><section class="pro-panel"><span class="eyebrow">Tipster</span><h2>@{{item.tipsterId?.name||'BraTipsters tipster'}}</h2><p class="muted">Review this contributor's broader performance before following a single prediction.</p><RouterLink to="/tipsters" class="btn btn-wide">Explore tipsters</RouterLink></section><section class="pro-panel"><span class="eyebrow">Match research</span><h3>Go beyond the selection</h3><p class="muted">View odds, xG, form, events, H2H and standings in the Football Match Centre.</p><RouterLink v-if="item.matchId?._id" :to="`/matches/${item.matchId._id}`" class="ghost btn-wide">Open Match Centre</RouterLink></section></aside></div>
    </template>
  </div></div>
</template>
<script setup lang="ts">import {onMounted,ref} from 'vue';import {RouterLink,useRoute} from 'vue-router';import {api} from '../services/api';import TeamLogo from '../components/TeamLogo.vue';const route=useRoute(),item=ref<any>(null),loading=ref(true);onMounted(async()=>{try{item.value=(await api.get(`/predictions/${route.params.id}`)).data}catch{}finally{loading.value=false}});</script>
