<template>
  <div class="pro-page page-animate subscription-pro"><div class="wrap">
    <section class="subscription-banner"><div><span class="eyebrow">BraTipsters Premium</span><h1>Football intelligence built for serious research.</h1><p>Move from a simple prediction feed to a deeper football research workspace with premium market context.</p></div><div class="subscription-trust"><b>SECURE CHECKOUT</b><span>Powered by Stripe</span><small>Card details never stored by BraTipsters</small></div></section>
    <div v-if="success" class="success-box">Payment completed. Stripe is confirming your subscription. Your account will update after the webhook is received.</div><div v-if="canceled" class="notice-strip">Checkout was canceled. You can choose a plan whenever you're ready.</div>
    <div v-if="auth.isLoggedIn&&current" class="membership-bar"><div><span>Current membership</span><b>{{current.plan}} · {{current.status}}</b></div><button class="ghost" @click="portal" :disabled="busy">Manage billing</button></div>
    <section class="plans-grid-pro"><article v-for="plan in plans" :key="plan.id" class="plan-pro" :class="{featured:plan.id==='premium'}"><div v-if="plan.id==='premium'" class="plan-popular">MOST POPULAR</div><span class="plan-tier">{{plan.id==='premium'?'Premium':'Lite'}}</span><h2>{{plan.name}}</h2><p>{{plan.description}}</p><div class="price-line"><strong>{{plan.monthlyConfigured?'Stripe':'—'}}</strong><span>monthly</span></div><ul><li>Football odds & market context</li><li>Live scores and match centre</li><li>Transparent prediction history</li><li>Dropping Odds intelligence</li><li v-if="plan.id==='premium'">Premium prediction content</li><li v-if="plan.id==='premium'">Deeper research workspace</li></ul><div class="plan-pro-actions"><button class="btn" :disabled="busy||!isConfigured(plan)" @click="checkout(plan.id,'month')">{{!auth.isLoggedIn?'Log in to subscribe':isConfigured(plan)?'Subscribe monthly':'Coming soon'}}</button><button class="ghost" v-if="isConfigured(plan,'year')" @click="checkout(plan.id,'year')">Yearly billing</button></div></article></section>
    <div class="subscription-features"><div><b>Live market monitoring</b><span>Track price movement and football odds signals.</span></div><div><b>Automatic results</b><span>Completed predictions move into the public record.</span></div><div><b>Stripe billing</b><span>Hosted checkout and customer portal for subscriptions.</span></div></div>
  </div></div>
</template>
<script setup lang="ts">import {computed,onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import {api} from '../services/api';import {useAuth} from '../stores/auth';import {useConfirm,useToast} from '../composables/feedback';const auth=useAuth(),{ask}=useConfirm(),{show:toast}=useToast(),route=useRoute(),router=useRouter(),plans=ref<any[]>([]),current=ref<any>(null),busy=ref(false);const success=computed(()=>route.query.success==='1'),canceled=computed(()=>route.query.canceled==='1');const isConfigured=(p:any,i='month')=>i==='year'?Boolean(p.yearlyConfigured):Boolean(p.monthlyConfigured);async function checkout(plan:string,interval:'month'|'year'){if(!auth.isLoggedIn){router.push({path:'/login',query:{redirect:'/subscription'}});return}busy.value=true;try{const d=await api.post('/billing/checkout',{plan,interval,successUrl:location.origin+'/subscription?success=1',cancelUrl:location.origin+'/subscription?canceled=1'});if(d.data?.url)location.href=d.data.url}catch(e:any){await ask({title:'BraTipsters checkout',message:e?.message||'Unable to start checkout.',confirmText:'Close',cancelText:'Dismiss',danger:true})}finally{busy.value=false}}async function portal(){busy.value=true;try{const d=await api.post('/billing/portal',{returnUrl:location.origin+'/subscription'});if(d.data?.url)location.href=d.data.url}catch(e:any){await ask({title:'BraTipsters checkout',message:e?.message||'Unable to start checkout.',confirmText:'Close',cancelText:'Dismiss',danger:true})}finally{busy.value=false}}onMounted(async()=>{try{plans.value=(await api.get('/billing/plans')).data||[]}catch{toast('Premium plans could not be loaded. Please refresh and try again.','error','Premium')}if(auth.isLoggedIn)try{current.value=(await api.get('/billing/me')).data?.subscription||null}catch{toast('Your current subscription could not be checked.','error','Premium')}});</script>
