<template>
  <section class="pro-panel td-simple-page">
    <div class="pro-section-head td-page-head"><div><span class="eyebrow">Account management</span><h1>Profile Settings</h1><p>Keep your tipster identity, public bio and expertise up to date. Your login email remains the same account identity.</p></div><span class="td-soft-badge">PROFILE</span></div>
    <form class="td-settings-form" @submit.prevent="save">
      <div class="td-settings-section"><div class="td-card-heading"><div><h2>Public profile</h2><p>These details appear on your public tipster profile.</p></div></div><div class="td-settings-grid"><div class="field"><label>Display name</label><input v-model="form.username" maxlength="60" required /></div><div class="field"><label>Country</label><input v-model="form.country" maxlength="80" placeholder="Ghana" /></div><div class="field td-field-full"><label>Bio</label><textarea v-model="form.bio" maxlength="600" placeholder="Tell members what you specialise in and how you approach football analysis."></textarea><small>{{ form.bio.length }}/600</small></div><div class="field"><label>Expertise</label><input v-model="form.expertise" placeholder="Corners, BTTS, Over 2.5" /></div><div class="field"><label>Profile photo URL</label><input v-model="form.profilePhoto" placeholder="https://…" /></div><div class="field td-field-full"><label>Social links</label><input v-model="form.socialLinks" placeholder="Instagram, X, Telegram — separate multiple links with commas" /></div></div></div>
      <div class="td-account-summary"><div><span>Account email</span><b>{{ auth.user?.email || '—' }}</b></div><div><span>Account type</span><b>Approved Tipster</b></div><div><span>Premium</span><b>Managed separately</b></div></div>
      <div class="td-submit-foot"><div><b>Profile updates are public</b><span>Use accurate, useful information that helps members understand your prediction style.</span></div><button class="btn" :disabled="saving">{{ saving ? 'Saving…' : 'Save profile →' }}</button></div>
      <div v-if="message" :class="messageType" class="mt-3">{{ message }}</div>
    </form>
  </section>
</template>
<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'; import { api } from '../services/api'; import { useAuth } from '../stores/auth'
const auth=useAuth(), saving=ref(false), message=ref(''), messageType=ref<'success'|'error'>('success'); const form=reactive({username:'',country:'',bio:'',expertise:'',profilePhoto:'',socialLinks:''});
function fill(profile:any){form.username=profile?.username||'';form.country=profile?.country||'';form.bio=profile?.bio||'';form.expertise=Array.isArray(profile?.expertise)?profile.expertise.join(', '):(profile?.expertise||'');form.profilePhoto=profile?.profilePhoto||'';form.socialLinks=Array.isArray(profile?.socialLinks)?profile.socialLinks.join(', '):(profile?.socialLinks||'')}
async function load(){try{fill((await api.get('/me/tipster')).data.profile)}catch{message.value='Unable to load your profile.';messageType.value='error'}}
async function save(){saving.value=true;message.value='';try{const d=await api.patch('/me/tipster/profile',{username:form.username,country:form.country,bio:form.bio,expertise:form.expertise.split(',').map(x=>x.trim()).filter(Boolean),profilePhoto:form.profilePhoto,socialLinks:form.socialLinks.split(',').map(x=>x.trim()).filter(Boolean)});fill(d.data); if (auth.user) auth.user.username=d.data.username; message.value=d.message||'Profile updated successfully.';messageType.value='success'}catch(e:any){message.value=e?.message||'Unable to update your profile.';messageType.value='error'}finally{saving.value=false}} onMounted(load)
</script>
